// <auto-generated />
using System;
using GameWeb.API.DbContextRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameWeb.API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameManager.Core.Domain.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("GamePrice")
                        .HasColumnType("float");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("GameId");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GameName = "Elden Ring",
                            GamePrice = 3999.0,
                            GenreId = 6,
                            ImageUri = "https://example.com/images/elden-ring.jpg",
                            ReleaseDate = new DateOnly(2022, 2, 25)
                        },
                        new
                        {
                            GameId = 2,
                            GameName = "Minecraft",
                            GamePrice = 1999.0,
                            GenreId = 5,
                            ImageUri = "https://example.com/images/minecraft.jpg",
                            ReleaseDate = new DateOnly(2011, 11, 18)
                        },
                        new
                        {
                            GameId = 3,
                            GameName = "GTA V",
                            GamePrice = 2999.0,
                            GenreId = 7,
                            ImageUri = "https://example.com/images/gta-v.jpg",
                            ReleaseDate = new DateOnly(2013, 9, 17)
                        },
                        new
                        {
                            GameId = 4,
                            GameName = "Red Dead Redemption 2",
                            GamePrice = 3499.0,
                            GenreId = 9,
                            ImageUri = "https://example.com/images/rdr2.jpg",
                            ReleaseDate = new DateOnly(2018, 10, 26)
                        },
                        new
                        {
                            GameId = 5,
                            GameName = "God of War Ragnarök",
                            GamePrice = 4999.0,
                            GenreId = 7,
                            ImageUri = "https://example.com/images/gow-ragnarok.jpg",
                            ReleaseDate = new DateOnly(2022, 11, 9)
                        },
                        new
                        {
                            GameId = 6,
                            GameName = "The Witcher 3",
                            GamePrice = 2499.0,
                            GenreId = 6,
                            ImageUri = "https://example.com/images/witcher-3.jpg",
                            ReleaseDate = new DateOnly(2015, 5, 19)
                        },
                        new
                        {
                            GameId = 7,
                            GameName = "Cyberpunk 2077",
                            GamePrice = 2999.0,
                            GenreId = 6,
                            ImageUri = "https://example.com/images/cyberpunk.jpg",
                            ReleaseDate = new DateOnly(2020, 12, 10)
                        },
                        new
                        {
                            GameId = 8,
                            GameName = "Forza Horizon 5",
                            GamePrice = 3499.0,
                            GenreId = 4,
                            ImageUri = "https://example.com/images/forza-horizon-5.jpg",
                            ReleaseDate = new DateOnly(2021, 11, 9)
                        },
                        new
                        {
                            GameId = 9,
                            GameName = "Call of Duty Modern Warfare",
                            GamePrice = 3999.0,
                            GenreId = 10,
                            ImageUri = "https://example.com/images/cod-mw.jpg",
                            ReleaseDate = new DateOnly(2019, 10, 25)
                        },
                        new
                        {
                            GameId = 10,
                            GameName = "FIFA 23",
                            GamePrice = 4599.0,
                            GenreId = 3,
                            ImageUri = "https://example.com/images/fifa-23.jpg",
                            ReleaseDate = new DateOnly(2022, 9, 30)
                        },
                        new
                        {
                            GameId = 11,
                            GameName = "Assassin’s Creed Valhalla",
                            GamePrice = 3999.0,
                            GenreId = 6,
                            ImageUri = "https://example.com/images/ac-valhalla.jpg",
                            ReleaseDate = new DateOnly(2020, 11, 10)
                        },
                        new
                        {
                            GameId = 12,
                            GameName = "Horizon Forbidden West",
                            GamePrice = 4999.0,
                            GenreId = 6,
                            ImageUri = "https://example.com/images/horizon-fw.jpg",
                            ReleaseDate = new DateOnly(2022, 2, 18)
                        },
                        new
                        {
                            GameId = 13,
                            GameName = "PUBG",
                            GamePrice = 1499.0,
                            GenreId = 10,
                            ImageUri = "https://example.com/images/pubg.jpg",
                            ReleaseDate = new DateOnly(2017, 12, 20)
                        },
                        new
                        {
                            GameId = 14,
                            GameName = "Skyrim",
                            GamePrice = 1999.0,
                            GenreId = 2,
                            ImageUri = "https://example.com/images/skyrim.jpg",
                            ReleaseDate = new DateOnly(2011, 11, 11)
                        },
                        new
                        {
                            GameId = 15,
                            GameName = "Among Us",
                            GamePrice = 499.0,
                            GenreId = 8,
                            ImageUri = "https://example.com/images/among-us.jpg",
                            ReleaseDate = new DateOnly(2018, 6, 15)
                        });
                });

            modelBuilder.Entity("GameManager.Core.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Fighting"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Roleplaying"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Sports"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Racing"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Kids and Family"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Action RPG"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Action Adventure"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Multiplayer"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Open World"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "FPS"
                        });
                });

            modelBuilder.Entity("GameManager.Core.Domain.Entities.Game", b =>
                {
                    b.HasOne("GameManager.Core.Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
